################################
#             格式             #
################################
#  - <世界名>,<x坐标>,<y坐标>,<z坐标>|<title原Json内容>

################################
#             变量             #
################################
# %PLAYER% - 玩家ID
# %WORLD%  - 世界名

messages:
  - world,0,100,0|{"text":"你好啊 %PLAYER%", "color":"gold"}